name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
 
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install, build, and test
      run: npm install --if-present
      run: npm rebuild --if-present
      run: npm run prepare --if-present
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
